version: '2'
services:
  jhipsterdemo1-app:
    image: jhipsterdemo1
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://jhipsterdemo1-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=jhipsterDemo1
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipsterdemo1-mongodb:
    extends:
      file: mongodb.yml
      service: jhipsterdemo1-mongodb
